name: Business Registry UI CI

on:
  pull_request:
    paths:
      - "web/business-registry-dashboard/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./web/business-registry-dashboard

jobs:
  business-registry-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "business-registry-ui"
      working_directory: "./web/business-registry-dashboard"
      codecov_flag: "businessregistryui"
